name: 'Node Build, Package, Publish'
inputs:
  node-version:
    required: true
  service-name:
    required: true
  revision:
    required: true
  aws-region:
    required: true
  aws-role:
    required: true


runs:
  using: "composite"
  steps:

    - id: checkout
      name: checkout
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}      

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: buildAndUnityTest
      uses: CailleachOrg/tfc-shared-actions/.github/actions/node/node-build@main
      with:
        node-version: ${{ inputs.node-version }}

    - name: Docker build
      shell: bash
      run: docker build -t ${{ steps.login-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.revision }} .

    - name: Docker push
      shell: bash
      run: docker push ${{ steps.login-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.revision }}