name: 'ECR Copy Image'
description: ""
inputs:
  from-role:
    required: true
  from-region:
    required: true
  to-role:
    required: true
  to-region:
    required: true
  service-name:
    required: true
  tag:
    required: true

runs:
  using: "composite"
  steps:

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.from-aws-role }}
        aws-region: ${{ inputs.from-aws-region }}      

    - name: Login to Origin Amazon ECR
      id: login-origin-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Pull from origin ECR
      shell: bash
      run: docker pull ${{ steps.login-origin-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.tag }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.to-aws-role }}
        aws-region: ${{ inputs.to-aws-region }}      

    - name: Login to Target Amazon ECR
      id: login-target-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Check if image exist in target
      continue-on-error: true
      id: check-image
      shell: bash
      run: aws ecr list-images --repository-name ${{ steps.login-target-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.tag }} 

    - name: Push to target ECR
      if: steps.check-image.outcome == 'failure'
      shell: bash
      run: |
        docker tag ${{ steps.login-origin-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.tag }}  ${{ steps.login-target-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.tag }} 
        docker push ${{ steps.login-target-ecr.outputs.registry }}/${{inputs.service-name}}:${{ inputs.tag }} 
