name: 'AWS Create service role'
description: "Create a role for a service"
inputs:
  country:
    required: true
  environment:
    required: true
  service-name:
    required: true
  service-type:
    required: true
  region:
    required: true
  role:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - name: Check if role exists
      continue-on-error: true
      shell: bash
      run: aws iam get-role --role-name ${{inputs.country}}-${{inputs.environment}}-${{inputs.service-name}}-role

    - name: Create AWS IAM role
      if: failure()
      shell: bash
      run: |

        sed -i 's/__AWS_SERVICE__/${{inputs.service-type}}/g' ${{github.action_path}}/policy.json

        aws iam create-role \
          --role-name ${{inputs.country}}-${{inputs.environment}}-${{inputs.service-name}}-role \
          --assume-role-policy-document file://${{github.action_path}}/policy.json