name: 'Create Organization Variable'
description: 'Invoke GitHub API to create variable in Organization.'
inputs:
  organizationName:
    description: 'GitHub organization name'
    required: true
  name:
    description: 'Variable name'
    required: true
  value:
    description: 'Variable value'
    required: true
secrets:
  token:
    description: 'GitHub Organization Token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'
