name: 'StarterECSPullRequest'

on:  
  workflow_call:
    secrets:
      tfc-token:
        required: true


jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4
      
    - name: "Terraform DEV Plan"
      uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-starter-plan@updateWorkflow
      with:
        tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
        tfc-token: "${{ secrets.tfc-token }}"
        tfc-workspace: "aws-ecs-starter-dev"
        environment: "** DEV **"
        message: "${{ github.event.pull_request.title }}"

    - name: "Terraform HML Plan"
      uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-starter-plan@updateWorkflow
      with:
        tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
        tfc-token: "${{ secrets.tfc-token }}"
        tfc-workspace: "aws-ecs-starter-hml"
        environment: "** HML **"
        message: "${{ github.event.pull_request.title }}"

    - name: "Terraform PRD Plan"
      uses: CailleachOrg/tfc-shared-actions/.github/actions/tfc/tfc-starter-plan@updateWorkflow
      with:
        tfc-organization: "${{ vars.TFC_ORGANIZATION }}"
        tfc-token: "${{ secrets.tfc-token }}"
        tfc-workspace: "aws-ecs-starter-prd"
        environment: "** PRD **"
        message: "${{ github.event.pull_request.title }}"
