name: 'StarterECSPushMain'

on:  
  workflow_call:
    inputs:
      organization:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      tfc-token:
        required: true

permissions:
  contents: read
  id-token: write

jobs:

  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4
     
    - id: tfc-apply
      name: "Terraform Apply"
      uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-starter-apply@main
      with:
        tfc-organization: "${{ inputs.organization }}"
        tfc-token: "${{ secrets.tfc-token }}"
        tfc-workspace: "aws-ecs-starter-${{ inputs.environment }}"
        message: "Creating infrastructure in ${{ inputs.environment }} environment"

    - name: Save projectName variable
      if: false
      uses: cailleach-devops/tfc-shared-actions/.github/actions/git/git-create-org-variable@main
      with:
        organizationName: ${{ vars.GH_VARIABLE_ORGANIZATION }}
        name: "PROJECT_NAME"
        value: ${{ steps.tfc-apply.outputs.projectName }}
        token: ${{ secrets.GIT_VARIABLE_TOKEN}}      

