name: 'NodePullRequest'

on:  
  workflow_call:
    inputs:
      tfc-organization:
        type: string
        required: true
    secrets:
      tfc-token:
        required: true

env:
  environment: 'dev'

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4
      
    - name: "Terraform Plan"
      uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-plan@main
      with:
        tfc-organization: ${{ inputs.tfc-organization }}
        tfc-token: ${{ secrets.tfc-token }}
        tfc-workspace: "${{github.event.repository.name}}-${{ env.environment }}"
        scriptOrigin: ${{ env.environment }}
        message: ${{ github.event.pull_request.title }}

  app-build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4

    - name: buildAndUnityTest
      uses: cailleach-devops/tfc-shared-actions/.github/actions/node/node-build@main
      with:
        node-version: '20.x'
