name: 'TestCreateOrgVariable'

on:  
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

  create-role:
    runs-on: ubuntu-latest
    steps:
    - name: "Create Variable"
      uses: cailleach-devops/tfc-shared-actions/.github/actions/git/git-create-org-variable@main
      with:
        organizationName: "${{ vars.GIT_ORGANIZATION }}"        
        name: "TestVar"
        value: "TestValue"
        token: "${{ secrets.GH_VARIABLE_TOKEN }}"
